import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/Sidebar";
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const Hanken = Hanken_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-hanken"
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Hanken.variable} font-hanken grid grid-cols-[270px_1fr] min-h-screen`}
      >
        <Sidebar />
        <div className="w-full h-full bg-[#F3F7FF]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
